### PR TITLE
appveyor.yml CI and x64 build

### PR DESCRIPTION
**Pull request by chcg**
- initial appveyor.yml CI config, see https://ci.appveyor.com/project/chcg/nppregextractor/build/1.0.6
- initial support for x64 build
- dllexport partly taken/merged from https://github.com/kbilsted/NotepadPlusPlusPluginPack.Net/tree/master/Visual%20Studio%20Project%20Template%20C%23/PluginInfrastructure, which needs dotnet framework 4.0
- added the RegExTractor_V1.3.4.zip for the appveyor build for all variants, maybe the build result is not functional for x64

### CODE REVIEW

**Comment by viper3400** [comment]
Thanks for contributing, @chcg. Will have a look at this these days and try to get the plug-in functional for x64. Have to read through https://github.com/bruderstein/npp-plugins-x64 first.

**Comment by chcg** [comment]
@viper3400  See https://github.com/bruderstein/npp-plugins-x64/blob/master/plugins/plugins_template.xml#L1552, the template is created from the win32 config at https://npppm.bruderste.in/plugins/view/nppregextractor and adapted to x64. I could add this section for you, if you have a release zip for x64 available.

What I have tested already is the startup of the plugin within n++. Just didn't test a real search.

**Comment by viper3400** [comment]
@chcg: Okay, got it. As NppRegExTractor is just a wrapper for my RegExTractor project it's not necessary to create a x64 version for the latter at the moment. 

Based on your pull request I've created an appveyor build job which produces two ZIPs (x86/x64) containing the necessary content.

The x64 link to version 2.0.0 ZIP of the plugin is: https://github.com/viper3400/NppRegExTractor/releases/download/2.0.0/NppRegExTractor_2.0.0_BUILD_2_x64.zip

NppRegExTractorPlugin.dll needs to be copied into $PLUGINDIR$, the files from sub directory RegExTractor needs to be copied into $PLUGINDIR$\RegExTractor.

Would be pleased if you could add this version into xml file.

Thx, Jan.

**Comment by chcg** [comment]
Done with https://github.com/bruderstein/npp-plugins-x64/commit/7af50e14fc742c2462c0c57dc0efb61234158902.

**Pull request merged**
